<a href="https://colab.research.google.com/github/lsneerg/pandas_exercises/blob/master/04_Apply/Students_Alcohol_Consumption/Exercises_suny.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [2]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'
df = pd.read_csv(url)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [4]:
df.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [5]:
df = df.loc[:, 'school':'guardian']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   school    395 non-null    object
 1   sex       395 non-null    object
 2   age       395 non-null    int64
 3   address   395 non-null    object
 4   famsize   395 non-null    object
 5   Pstatus   395 non-null    object
 6   Medu      395 non-null    int64
 7   Fedu      395 non-null    int64
 8   Mjob      395 non-null    object
 9   Fjob      395 non-null    object
 10  reason    395 non-null    object
 11  guardian  395 non-null    object
dtypes: int64(3), object(9)
memory usage: 37.2+ KB

In [7]:
df.describe()

              age        Medu        Fedu
count  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519
std      1.276043    1.094735    1.088201
min     15.000000    0.000000    0.000000
25%     16.000000    2.000000    2.000000
50%     17.000000    3.000000    2.000000
75%     18.000000    4.000000    3.000000
max     22.000000    4.000000    4.000000

In [8]:
df.sample(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
83,GP,M,15,U,LE3,T,2,2,services,services,home,mother
269,GP,F,18,R,GT3,T,2,1,other,other,reputation,mother
86,GP,F,16,U,LE3,T,2,2,at_home,other,course,mother
200,GP,F,16,U,GT3,T,4,3,health,other,home,mother
194,GP,M,16,U,GT3,T,2,3,other,other,home,father

### Step 5. Create a lambda function that will capitalize strings.

In [13]:
cap = lambda x: x.capitalize() if isinstance(x, str) else x

### Step 6. Capitalize both Mjob and Fjob

In [24]:
df[['Mjob', 'Fjob']] = df[['Mjob', 'Fjob']].map(cap)

In [25]:
df.sample(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
85,GP,F,15,U,GT3,T,4,4,Services,Services,reputation,father,False
105,GP,F,15,U,GT3,A,3,3,Other,Health,reputation,father,False
323,GP,F,17,U,GT3,T,3,1,Services,Services,course,father,False
206,GP,F,16,U,GT3,A,3,1,Services,Other,course,mother,False
377,MS,F,18,R,LE3,T,4,4,Teacher,Services,course,mother,True

### Step 7. Print the last elements of the data set.

In [26]:
df.tail(1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father,True

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [20]:
majority = lambda x: x > 17

In [21]:
df['legal_drinker'] = df['age'].map(majority)

In [22]:
df.sample(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
84,GP,F,15,U,GT3,T,1,1,Other,Other,home,father,False
6,GP,M,16,U,LE3,T,2,2,Other,Other,home,mother,False
221,GP,F,17,U,GT3,T,1,1,At_home,Other,reputation,mother,False
45,GP,F,15,U,LE3,A,4,3,Other,Other,course,mother,False
337,GP,F,17,U,GT3,T,3,2,Other,Other,home,mother,False
173,GP,F,16,U,GT3,T,1,3,At_home,Services,home,mother,False
358,MS,M,18,U,LE3,T,1,1,Other,Services,home,father,True
107,GP,M,16,U,GT3,T,3,3,Services,Other,home,father,False
379,MS,F,17,R,GT3,T,3,1,At_home,Other,reputation,mother,False
81,GP,M,15,U,GT3,T,2,3,Other,Other,home,mother,False

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [29]:
df.map(lambda x: x * 10 if isinstance(x, int) else x)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,course,mother,10
1,GP,F,170,U,GT3,T,10,10,At_home,Other,course,father,0
2,GP,F,150,U,LE3,T,10,10,At_home,Other,other,mother,0
3,GP,F,150,U,GT3,T,40,20,Health,Services,home,mother,0
4,GP,F,160,U,GT3,T,30,30,Other,Other,home,father,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,Services,Services,course,other,10
391,MS,M,170,U,LE3,T,30,10,Services,Services,course,mother,0
392,MS,M,210,R,GT3,T,10,10,Other,Other,course,other,10
393,MS,M,180,R,LE3,T,30,20,Services,Other,course,mother,10
394,MS,M,190,U,LE3,T,10,10,Other,At_home,course,father,10