<a href="https://colab.research.google.com/github/lsneerg/pandas_exercises/blob/master/04_Apply/US_Crime_Rates/Exercises_suny.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.

In [2]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv'
crime = pd.read_csv(url)

In [3]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     int64
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: int64(12)
memory usage: 5.3 KB

In [4]:
crime.sample(10)

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
42,2002,287973924,11878954,1423677,10455277,16229,95235,420806,891407,2151252,7057370,1246646
12,1972,208230000,8248800,834900,7413900,18670,46850,376290,393090,2375500,4151200,887200
5,1965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
36,1996,265228572,13493863,1688540,11805300,19650,96250,535590,1037050,2506400,7904700,1394200
23,1983,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
15,1975,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
10,1970,203235298,8098000,738820,7359200,16000,37990,349860,334970,2205000,4225800,928400
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
50,2010,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565

### Step 4. What is the type of the columns?

In [5]:
crime.dtypes

Year                  int64
Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [18]:
crime.Year = pd.to_datetime(crime['Year'], format='%Y')

In [19]:
crime.sample(5)

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
40,2000-01-01,281421906,11608072,1425486,10182586,15586,90178,408016,911706,2050992,6971590,1160002
26,1986-01-01,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
9,1969-01-01,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500
29,1989-01-01,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
53,2013-01-01,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294

### Step 6. Set the Year column as the index of the dataframe

In [22]:
crime.set_index('Year', inplace=True)

In [23]:
crime.sample(5)

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
2004-01-01,293656842,11679474,1360088,10319386,16148,95089,401470,847381,2144446,6937089,1237851
2009-01-01,307006550,10762956,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
1983-01-01,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
1994-01-01,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
1973-01-01,209851000,8718100,875910,7842200,19640,51400,384220,420650,2565500,4347900,928800

### Step 7. Delete the Total column

In [28]:
crime.drop('Total', axis=1, inplace=True)

In [29]:
crime.sample(5)

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,
1978-01-01,218059000,1085550,10123400,19560,67610,426930,571460,3128300,5991000,1004100
1986-01-01,240132887,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
1975-01-01,213124000,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
2009-01-01,307006550,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
1992-01-01,255082000,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800

In [38]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 55 entries, 1960-01-01 to 2014-01-01
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Population          55 non-null     int64
 1   Violent             55 non-null     int64
 2   Property            55 non-null     int64
 3   Murder              55 non-null     int64
 4   Forcible_Rape       55 non-null     int64
 5   Robbery             55 non-null     int64
 6   Aggravated_assault  55 non-null     int64
 7   Burglary            55 non-null     int64
 8   Larceny_Theft       55 non-null     int64
 9   Vehicle_Theft       55 non-null     int64
dtypes: int64(10)
memory usage: 6.8 KB

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

In [46]:
grouped = crime.groupby(pd.Grouper(axis=0, freq="10YS")).agg(lambda x: x.mean() if x.name == 'Population' else x.sum())
grouped.index = grouped.index.strftime('%Y')

In [47]:
grouped

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,
1960,191505317.5,4134930,45160900,106180,236720,1633510,2158520,13321100,26547700,5292100
1970,212119329.8,9607930,91383800,192230,554570,4159020,4702120,28486000,53157800,9739900
1980,237137006.9,14074328,117048900,206439,865639,5383109,7619130,33073494,72040253,11935411
1990,261282525.8,17527048,119053499,211664,998827,5748930,10568963,26750015,77679366,14624418
2000,294796911.7,13968056,100944369,163068,922499,4230366,8652124,21565176,67970291,11412834
2010,314029261.4,6072017,44095950,72867,421059,1749809,3764142,10125170,30401698,3569080

### Step 9. What is the most dangerous decade to live in the US?

In [53]:
grouped.idxmax(axis=0)

Population            2010
Violent               1990
Property              1990
Murder                1990
Forcible_Rape         1990
Robbery               1990
Aggravated_assault    1990
Burglary              1980
Larceny_Theft         1990
Vehicle_Theft         1990
dtype: object